language: node_js

node_js:
  - 6
  - 7
  - 8
  - 9
  - 10

sudo: false

before_install:
- npm install -g npm@latest
- npm install -g greenkeeper-lockfile
install: npm install
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
